### ISSUE TITLE
Fix unit tests in mnist.rs, cifar10.rs and imagenet_v2.rs 

### ISSUE THREAD

**Issue by mjovanc** [delta-rs/delta#62]
They are commented out right now since more work is needed here to get it right. I added some tests that I think is a good start. This is a good started issue or low hanging fruit IMO.

**Comment by RohitP2005** [comment]
Hello @mjovanc , I am willing to complete those tasks, is the issue still available or assigned to someone

**Comment by mjovanc** [comment]
> Hello @mjovanc , I am willing to complete those tasks, is the issue still available or assigned to someone
> 
> 

It's yours if you can do it! 👌🏻
