### ISSUE TITLE
Switch println to logging library

### ISSUE THREAD

**Issue by mjovanc** [delta-rs/delta#8]
Instead of writing println we should probably use a logging library with for example `info!()` etc.

For these kinds of output it should be for example `debug!`:

```
Decompressed file: .cache/data/mnist/train-images-idx3-ubyte.gz
Decompressed file: .cache/data/mnist/train-labels-idx1-ubyte.gz
Decompressed file: .cache/data/mnist/t10k-images-idx3-ubyte.gz
Decompressed file: .cache/data/mnist/t10k-labels-idx1-ubyte.gz
```

**Comment by pinguxx** [comment]
Just the standard log or you are thinking of log4rs or tracing?
